version: "3.9"

networks:
  bastion:
    name: ansible

services:

  bastion:
    image: ghcr.io/jervnorsk/jnt-ansible-bastion
    build:
      context: services/bastion
    volumes:
      - /run/docker.sock:/run/docker.sock
      - ./services:/srv/services
      - ./collections:/srv/ansible/collections
    working_dir: /srv/services/bastion/runtime
    deploy:
      replicas: 0
    networks:
      bastion:
