---
- name: "Spring Boot Automation Pipeline"
  hosts: "{{ on_hosts | default('localhost') }}"

  tasks:
    - tags:
        - present
        - started
        - up
      block:
        - name: "Installing service"
          include_role:
            name: spring_setup
          vars:
            spring_installation_state: present

    - tags:
        - started
        - up
      block:
        - name: "Starting service"
          include_role:
            name: spring_service
          vars:
            spring_service_state: started

    - tags:
        - absent
        - stopped
        - down
      block:
        - name: "Stopping service"
          include_role:
            name: spring_service
          vars:
            spring_service_state: stopped

    - tags:
        - absent
      block:
        - name: "Uninstalling service"
          include_role:
            name: spring_setup
          vars:
            spring_installation_state: absent
