---
- name: "Check arguments"
  assert:
    quiet: yes
    that:
      - wildfly_cli_remote_file is defined
      - wildfly_cli_remote_file.stat is defined

- name: "Retrieve remote files to execute"
  find:
    paths: "{{ wildfly_cli_remote_file.stat.path }}"
    file_type: file
    recurse: true
  register: wildfly_cli_remote_file_children

- block:
    - name: "Execute JBoss CLI files"
      loop: "{{ wildfly_cli_remote_file_children.files }}"
      shell:
        cmd: "{{ wildfly_home }}/bin/jboss-cli.sh -c --commands='run-batch --file={{ item.path }}'"
      register: wildfly_cli_errors
  always:
    - when:
        - wildfly_cli_errors is failed
      name: "Show JBoss CLI errors"
      loop: "{{ wildfly_cli_errors.results | selectattr('failed', 'defined') | selectattr('failed', 'equalto', true) }}"
      loop_control:
        label: "{{ item.item.path }}"
      debug:
        msg: "{{ item.stdout_lines }}"

