version: '3.9'

services:

  host:
    image: ghcr.io/jervnorsk/jnt-ansible-host-${with_os}
    build:
      context: /srv/services/host
      dockerfile: os/${with_os}/Dockerfile
    privileged: true
