---
- when:
    - wildfly_installation.present
  block:
    - when:
        - wildfly_configuration_files is defined
      block:
        - name: "Gathering configuration files facts"
          register: wildfly_configuration_local_facts
          with_items: "{{ wildfly_configuration_files.split(',') | list }}"
          ansible.builtin.stat:
            path: "{{ item }}"
          delegate_to: localhost

        - name: "Keeping configuration files present"
          with_items: "{{ wildfly_configuration_local_facts.results }}"
          when:
            - item.stat.exists
          ansible.builtin.copy:
            src: "{{ item.stat.path }}"
            dest: "{{ wildfly_configuration_path }}/"
