---
- name: "Check required arguments"
  assert:
    quiet: yes
    that:
      - wildfly_deployment_local_file is defined
      - wildfly_deployment_local_file.stat is defined

- name: "Upload local files to remote"
  copy:
    src: "{{ wildfly_deployment_local_file.stat.path }}"#/{{ wildfly_mode }}/"
    dest: "{{ wildfly_deployment_dir_path }}/"

- name: "Retrieve remote files state"
  stat:
    path: "{{ wildfly_deployment_dir_path }}"
  register: wildfly_deployment_remote_file
