version: '3.9'

networks:
  bastion:
    name: ansible
    external: true

services:

  ms:
    container_name: "${COMPOSE_PROJECT}-ms-${service_host_name}"
    extends:
      file: ../host/docker-compose.yml
      service: host
    networks:
      bastion:
    ports:
      - "${service_host_port}:${service_host_port}"
