---
- name: "JBoss Wildfly Automation Pipeline"
  hosts: "{{ on_hosts | default('localhost') }}"

  tasks:
    # TODO: setup must not autorun service until the tag up is not set
    - tags:
        - present
        - started
        - up
      block:
        - import_role:
            name: install
        - import_role:
            name: setup
        - include_role:
            name: wildfly_configuration
        - include_role:
            name: wildfly_lib

    - tags:
        - started
        - up
      block:
        - include_role:
            name: ctl
          vars:
            set_state_as: up
        - include_role:
            name: wildfly_cli
        - include_role:
            name: wildfly_module
        - include_role:
            name: wildfly_deployment

    - tags:
        - absent
        - stopped
        - down
      block:
        - include_role:
            name: ctl
          vars:
            set_state_as: down

    - tags:
        - absent
      include_role:
        name: uninstall
